default['whatsmydistrict']['app_name'] = 'whatsmydistrict'
default['whatsmydistrict']['app_root'] = '/opt/whatsmydistrict'
default['whatsmydistrict']['database']['db_name'] = 'districts'
default['whatsmydistrict']['database']['user'] = 'whatsmydistrict'
default['whatsmydistrict']['database']['password'] = 'password'
default['whatsmydistrict']['database']['host'] = '127.0.0.1'
